Banking/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('onlinebanking/', views.onlinebanking, name='onlinebanking'),
    path('applyforloan/', views.applyforloan, name='applyforloan'),
    path('statement/', views.statement, name='statement'),
    path('contactus/', views.contactus, name='contactus'),
    path('register/', views.registration_form, name='register'),
    path('profile/', views.profile, name='profile'),
    path('updateprofile/',views.update_profile,name='updateprofile'),
    path('login/',views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('adminlogin/',views.login_admin,name='adminlogin'),
    path('adminlogout/',views.logout_admin,name='adminlogout'),
    path('applications/', views.applications, name='applications'),
    path('loanapplications/',views.loan_application,name='loanapplications'),
    path('aprovedloanapplications/<int:loan_id>',views.approve_loan_application,name='approvedloanapplications'),
    path('declinedloanapplications/<int:loan_id>',views.declined_loan_application,name='declinedloanapplications'),
    path('payemi/<int:loan_id>/',views.pay_emi, name='pay_emi'),
    path('approve/<int:registration_id>/', views.approve_registration, name='approve_registration'),
    path('decline/<int:registration_id>/', views.decline_registration, name='decline_registration'),
    path('money-transfer/', views.money_transfer, name='moneytransfer'),
    path('moneytransferconfirm/', views.transfer_confirmation, name='moneytransferconfirm'),
    path('confirmotp', views.confirm_otp_transfer, name='confirmotp'),
    path('deposit/', views.deposit, name='deposit'),
    path('manage_beneficiaries/', views.manage_beneficiaries, name='manage_beneficiaries'),
    path('delete_beneficiary/<int:beneficiary_id>/', views.delete_beneficiary, name='delete_beneficiary'),
    path('fetch_user_details/', views.fetch_user_details, name='fetch_user_details'),
    path('otpverification/',views.otp_verification,name='otpverification'),
    path('send_otp/', views.send_otp_email, name='send_otp_email'),
    path('users/',views.total_users,name='users'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('help/',views.help,name='help'),
    path('reports/',views.reports,name='reports'),
    path('logout-on-unload/', views.logout_on_unload, name='logout_on_unload'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
import datetime

class BaseRegistration(models.Model):
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    username = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=100, unique=True)
    address1 = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    state = models.CharField(max_length=100, null=True)
    zip_code = models.CharField(max_length=10, null=True)
    initial_deposit = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    card_type = models.CharField(max_length=50, null=True)
    image = models.ImageField(upload_to='images/', null=True, blank=True, validators=[FileExtensionValidator(['jpg', 'jpeg', 'png'])])
    signature = models.ImageField(upload_to='signatures/', null=True, blank=True, validators=[FileExtensionValidator(['jpg', 'jpeg', 'png'])])
    gender = models.CharField(max_length=10, null=True)
    date_of_birth = models.DateField(null=True, default=datetime.date.today)
    phone_number = models.CharField(max_length=15, null=True)
    otp = models.CharField(max_length=6, null=True)
    marital_status = models.CharField(max_length=20, null=True)

    class Meta:
        abstract = True

class Transaction(models.Model):
    TRANSACTION_TYPES = [
        ('Deposit', 'Deposit'),
        ('Money Transfer', 'Money Transfer'),
        ('Loan Disbursement','Loan Disbursement'),
    ]

    account_number = models.CharField(max_length=8)
    transaction_type = models.CharField(max_length=255, choices=TRANSACTION_TYPES)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_type = models.CharField(max_length=20, null=True, blank=True)
    recipient_account = models.CharField(max_length=8, null=True, blank=True)
    deposit_details = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.transaction_type} of {self.amount} on {self.timestamp}"

class BankRegistrations(BaseRegistration):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=100, null=True)
    confirm_password = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class ApprovedRegistrations(BaseRegistration):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    account_number = models.IntegerField(unique=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class DeclinedRegistrations(BaseRegistration):
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class HomeBannerMain(models.Model):
    main_banner = models.ImageField(upload_to='images/', null=True, blank=True)
    banner_title = models.CharField(max_length=100, default="First Line<br>Second Line", blank=True)
    banner_description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.banner_title

class SubBanner(models.Model):
    sub_banner = models.ImageField(upload_to='images/', null=True, blank=True)
    sub_banner_title = models.CharField(max_length=100, null=True)
    sub_banner_description = models.TextField(null=True)

    def __str__(self):
        return self.sub_banner_title

class TrustedSecure(models.Model):
    trusted_secure = models.ImageField(upload_to='images/', null=True, blank=True)
    trusted_secure_title = models.CharField(max_length=100, null=True)
    trusted_secure_description = models.TextField(null=True)

    def __str__(self):
        return self.trusted_secure_title

class LatestNews(models.Model):
    news1 = models.ImageField(upload_to='images/', null=True, blank=True)
    news1_title = models.CharField(max_length=100, null=True)
    news1_description = models.TextField(null=True)

    def __str__(self):
        return self.news1_title

class Card(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    card_type = models.CharField(max_length=100, null=True)
    card_number = models.CharField(max_length=16)
    card_expiry = models.DateField(null=True)
    card_cvv = models.IntegerField(null=True)
    card_pin = models.IntegerField(null=True)
    card_background = models.ImageField(upload_to='images/', null=True, blank=True)


    def __str__(self):
        return str(f"{self.user.first_name} {self.user.last_name}")

class Feedback(models.Model):
    description = models.TextField(null=True)
    user_name = models.CharField(max_length=100, null=True)
    email = models.EmailField(null=True)

    def __str__(self):
        return self.user_name

class Email(models.Model):
    subject = models.CharField(max_length=100, null=True)
    message = models.TextField(null=True)
    def __str__(self):
        return self.subject


class LoanApplication(models.Model):
    LOAN_TYPES = [
        ('Personal Loan', 'Personal Loan'),
        ('Home Loan', 'Home Loan'),
        ('Car Loan', 'Car Loan'),
    ]
    STATUS=[
        ('Pending','Pending'),
        ('Declined','Declined'),
        ('In Progress','In Progress'),
        ('Paid','Paid')
    ]


    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    email = models.EmailField(null=True)
    phone_number = models.CharField(max_length=15, null=True)
    loan_type = models.CharField(max_length=250, choices=LOAN_TYPES)
    loan_amount = models.DecimalField(max_digits=10, decimal_places=2,null=True)
    interest_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True)
    loan_tenure = models.IntegerField(null=True)
    monthly_emi = models.IntegerField( blank=True, null=True)
    employment_status = models.CharField(max_length=20)
    annual_income = models.DecimalField(max_digits=10, decimal_places=2,null=True)
    account_number = models.CharField(max_length=20,null=True)
    additional_info = models.TextField(blank=True, null=True)
    application_date = models.DateTimeField(auto_now_add=True)
    total_amount_due = models.IntegerField( blank=True, null=True)
    calculated_interest = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    status=models.CharField(max_length=20,choices=STATUS)

    def __str__(self):
        return f"{self.user.username} - {self.loan_type} - {self.application_date}"

class ApprovedLoans(models.Model):
    LOAN_TYPES = [
        ('personal', 'Personal Loan'),
        ('home', 'Home Loan'),
        ('car', 'Car Loan'),
    ]
    STATUS = [
        ('Pending', 'Pending'),
        ('Declined', 'Declined'),
        ('In Progress', 'In Progress'),
        ('Paid', 'Paid')
    ]
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    loan_type = models.CharField(max_length=250, choices=LOAN_TYPES,null=True)
    loan_amount = models.DecimalField(max_digits=10, decimal_places=2,null=True)
    interest_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True)
    loan_tenure = models.IntegerField(null=True)
    monthly_emi = models.IntegerField( blank=True, null=True)
    total_amount_due = models.IntegerField( blank=True, null=True)
    calculated_interest = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS)

    def __str__(self):
        return f"{self.user.username}"


class HelpTicket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    full_name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

    CATEGORY_CHOICES = [
        ('transaction_complaint', 'Transaction Complaint'),
        ('loan_assistance', 'Loan Assistance'),
        ('other', 'Other'),
        ('loan_application', 'Loan Application'),
    ]

    LOAN_TYPE_CHOICES = [
        ('personal', 'Personal Loan'),
        ('car', 'Car Loan'),
        ('home', 'Home Loan'),
    ]

    PAYMENT_TYPE_CHOICES = [
        ('transfer', 'Money Transfer'),
        ('deposit', 'Deposit'),
        ('emi', 'EMI'),
    ]

    PAYMENT_STATUS_CHOICES = [
        ('failed', 'Payment Failed'),
        ('complete_not_received', 'Payment Complete but Not Received'),
        ('pending', 'Payment Pending'),
        ('refunded', 'Payment Refunded'),
        ('processing', 'Payment Processing'),
        ('cancelled', 'Payment Cancelled'),
    ]

    LOAN_STATUS_CHOICES = [
        ('pending_approval', 'Pending Approval'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
        ('disbursed', 'Disbursed'),
        ('repaid', 'Repaid'),
        ('defaulted', 'Defaulted'),
    ]

    EMI_STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('paid', 'Paid'),
        ('partial', 'Partial Payment'),
        ('late', 'Late Payment'),
        ('defaulted', 'Defaulted'),
    ]

    ALL_CHOICES = LOAN_TYPE_CHOICES + PAYMENT_TYPE_CHOICES
    ALL_CHOICES_2 = LOAN_STATUS_CHOICES + PAYMENT_STATUS_CHOICES + EMI_STATUS_CHOICES

    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    sub_category_1 = models.CharField(max_length=50, choices=ALL_CHOICES, null=True, blank=True)
    sub_category_2 = models.CharField(max_length=50, choices=ALL_CHOICES_2, null=True, blank=True)
    recent_transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE, null=True, blank=True)

    message = models.TextField()

    STATUS_CHOICES = [('open', 'Open'), ('closed', 'Closed')]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='open')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

myapp/forms.py
from django import forms
from .models import ApprovedRegistrations

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = ApprovedRegistrations
        fields = ['first_name', 'last_name', 'phone_number', 'address1', 'city', 'state', 'image', 'signature', 'password', 'confirm_password']

myapp/templates/adminlogin.html
<!DOCTYPE html>
        {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>

    <!-- Bootstrap CSS (You can replace the CDN with a local Bootstrap file if needed) -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- Font Awesome CSS (You can replace the CDN with a local Font Awesome file if needed) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f5f5f5;
            color: #333;
            margin: 0;
            padding: 0;
        }

        .navbar {
            width: 100%;
            background-color: #0D47A1;
        }

        .navbar .navbar-brand {
            color: #ffffff;
            font-size: 1rem;
        }

        .navbar .nav-link {
            color: #ffffff;
            font-size: 1rem;
        }

        .navbar .nav-link:hover {
            color: #80D8FF;
        }

        .navbar-toggler-icon {
            background-color: #ffffff;
        }

        .custom-form {
            background-color: #f8f9fa;
            padding: 30px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            margin: auto;
        }

        .custom-form label {
            font-weight: bold;
        }

        .custom-form input[type="text"],
        .custom-form input[type="password"] {
            width: 100%;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ced4da;
            margin-bottom: 10px;
        }

        .custom-form button[type="submit"] {
            width: 100%;
            padding: 10px;
            border-radius: 5px;
            border: none;
            background-color: #007bff;
            color: #fff;
            text-align: center;
            cursor: pointer;
        }

        .custom-form button[type="submit"]:hover {
            background-color: #0056b3;
        }

        .center-form-group {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        @media (max-width: 576px) {
            .custom-form {
                padding: 15px;
                max-width: none;
            }
        }

        body {

            background: #f5f5f5;
        }

        .heading h2 {
            font-size: 2rem;
            margin-bottom: 20px;
        }

        .custom-form button[type="submit"] {
            /* Improve button styling */
            width: 100%;
            padding: 12px;
            border-radius: 8px;
            border: none;
            background-color: #007bff;
            color: #fff;
            text-align: center;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .custom-form button[type="submit"]:hover {

            background-color: #0056b3;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'dashboard' %}"><img src="{% static 'img/BankLogo.png' %}" height="40px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <div class="flex-grow-1"></div>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> Login</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container mt-5">
    <div class="heading center-form-group">
        <h2 style="color: #0070cc">Admin Login</h2>
    </div>
    <form class="custom-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>

        <button type="submit" class="btn btn-primary">Login</button>
        <div class="center-form-group mt-2">
            <p>Forgot your password? <a href="#">Reset Password</a></p>
        </div>
    </form>


</div>

{% if messages %}
<div class="container mt-3">
    <div class="alert alert-success" role="alert">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
    </div>
</div>
{% endif %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<!-- Example script for Chart.js (Include your specific chart library script here) -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</body>

</html>

myapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Banking Website</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
    {% include 'navbar.html' %}
    {% block body %}
      <h1>Base Page</h1>
    {% endblock %}
    {% include 'footer.html' %}

    <!-- Bootstrap JS (Optional) -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/help.html
{% extends 'base.html' %}
{% block title %}Banking Help / Ticket{% endblock %}
{% block body %}
<style>
    .container1 {
        margin: 20px auto;
        padding: 20px;
        background-color: #f8f9fa;
        border-radius: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    }

    h1 {
        color: #007bff;
    }

    p {
        margin-bottom: 20px;
    }

    .form-container,
    .status-section {
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        margin-bottom: 30px;
        background-color: #fff;
    }

    label {
        font-weight: bold;
        color: #555;
    }

    input[type="text"],
    input[type="email"],
    input[type="tel"],
    input[type="number"],
    select,
    textarea {
        width: 100%;
        padding: 12px;
        border-radius: 5px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        box-sizing: border-box;
    }

    input[type="submit"] {
        width: 100%;
        padding: 15px;
        border-radius: 5px;
        border: none;
        background-color: #007bff;
        color: #fff;
        text-align: center;
        cursor: pointer;
    }

    input[type="submit"]:hover {
        background-color: #0056b3;
    }

    .status-section {
        background-color: #f2f2f2;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }
</style>

<div class="container1">
    <div class="row">
        <div class="col-md-6">
            <div class="form-container">
                <h1 style="color: #0D47A1">Banking Help / Ticket</h1>
                <p>Submit a help ticket to get assistance with your banking-related inquiries.</p>
                {% if user.is_authenticated %}
                <form class="form" method="POST">
                    {% csrf_token %}
                    <div class="mb-4">
                        <div class="d-flex flex-column">
                            <div class="mb-3">
                                <span class="fw-bold">Full Name :</span> {{ user.first_name }} {{ user.last_name }}
                            </div>
                            <div class="mb-3">
                                <span class="fw-bold">Email :</span> {{ user.email }}
                            </div>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="category">Category</label>
                        <select class="form-select" id="category" name="category" required>
                            <option value="" selected disabled>Select Option</option>
                            <option value="transaction_complaint">Transaction Complaint</option>
                            <option value="loan_assistance">Loan Assistance</option>
                            <option value="other">Other</option>
                        </select>
                    </div>
                    <div class="mb-3" id="recentTransactionsContainer" style="display: none;">
                        <label for="recentTransactions">Recent Transactions</label>

                        <select class="form-select" id="recentTransactions" name="recentTransactions">
                            <option value="" selected disabled>Select Transaction</option>
                            {% for transaction in transactions %}
                            <option value="{{ transaction.id }}">
                                <table>
                                    <tr>
                                        <td>Transaction ID :</td>
                                        <td>{{ transaction.id }}</td>
                                    </tr>
                                    <tr>
                                        <td>Type :</td>
                                        <td>{{ transaction.get_transaction_type_display }}</td>
                                    </tr>
                                    <tr>
                                        <td>Amount :</td>
                                        <td>{{ transaction.amount }}</td>
                                    </tr>
                                    <tr>
                                        <td>Date :</td>
                                        <td>{{ transaction.timestamp }}</td>
                                    </tr>
                                </table>
                            </option>
                            {% endfor %}
                        </select>
                        <div class="mb-3" id="paymentStatusContainer" style="display: none;">
                            <label for="paymentStatus">Payment Status</label>
                            <select class="form-select" id="paymentStatus" name="paymentStatus">
                                <option value="" selected disabled>Select Payment Status</option>
                                <option value="failed">Payment Failed</option>
                                <option value="complete_not_received">Payment Complete but Not Received</option>
                                <option value="pending">Payment Pending</option>
                                <option value="refunded">Payment Refunded</option>
                                <option value="processing">Payment Processing</option>
                                <option value="cancelled">Payment Cancelled</option>
                            </select>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="message">Your Message</label>
                        <textarea class="form-control" id="message" name="message" rows="4" required></textarea>
                    </div>
                    <script>
                        document.addEventListener("DOMContentLoaded", function () {
                            var categoryDropdown = document.getElementById("category");
                            var recentTransactionsContainer = document.getElementById("recentTransactionsContainer");
                            var paymentStatusContainer = document.getElementById("paymentStatusContainer");
                            var recentTransactionsDropdown = document.getElementById("recentTransactions");

                            categoryDropdown.addEventListener("change", function () {
                                if (categoryDropdown.value === "transaction_complaint") {
                                    recentTransactionsContainer.style.display = "block";
                                } else {
                                    recentTransactionsContainer.style.display = "none";
                                    paymentStatusContainer.style.display = "none";
                                }
                            });

                            recentTransactionsDropdown.addEventListener("change", function () {
                                if (recentTransactionsDropdown.value !== "") {
                                    paymentStatusContainer.style.display = "block";
                                } else {
                                    paymentStatusContainer.style.display = "none";
                                }
                            });
                        });
                    </script>
                    <button type="submit" class="btn btn-primary">Submit Ticket</button>
                </form>
                {% else %}
                <form class="form" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="fullName">Full Name</label>
                        <input type="text" class="form-control" id="fullName" name="fullName" required>
                    </div>

                    <div class="mb-3">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>

                    <div class="mb-3">
                        <label for="phone">Phone Number</label>
                        <input type="tel" class="form-control" id="phone" name="phone" required>
                    </div>

                    <div class="mb-3">
                        <label for="category">Category</label>
                        <select class="form-select" id="category" name="category" required>
                            <option value="account_creation">Account Creation</option>
                            <option value="other">Other</option>
                        </select>
                    </div>

                    <div class="mb-3">
                        <label for="message">Your Message</label>
                        <textarea class="form-control" id="message" name="message" rows="4" required></textarea>
                    </div>

                    <button type="submit" class="btn btn-primary">Submit Ticket</button>
                </form>
                {% endif %}
            </div>
        </div>

        <div class="col-md-6">
            <div class="status-section">
                <h2 style="color: #0D47A1">Complaint Status</h2>
                <p>Enter your ticket ID to check the status:</p>
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="ticketId">Ticket ID:</label>
                        <input type="text" class="form-control" id="ticketId" name="ticketId" required>
                    </div>

                    <button type="submit" class="btn btn-primary">Check Status</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% if messages %}
<div class="container mt-3">
    <div class="alert alert-success" role="alert">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}

myapp/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Beneficiary List</h2>
                    <button id="showBeneficiaryBtn" class="btn btn-primary btn-block mb-3">Show Beneficiary List</button>
                    <ul id="beneficiaryList" class="list-group">
                        {% for beneficiary in beneficiary_list %}
                            <li class="list-group-item">{{ beneficiary.name }} - {{ beneficiary.account_number }} - {{ beneficiary.bank_name }}{% if beneficiary.ifsc_code %} - {{ beneficiary.ifsc_code }}{% endif %}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
</body>
</html>